AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

# Exclude generated/vendor files
  Exclude:
    - "vendor/**/*"
    - "spec/dummy/bin/**/*"
    - "spec/dummy/config/puma.rb"
    - "spec/dummy/config/environments/**/*"
    - "spec/dummy/config/initializers/**/*"
    - "spec/dummy/db/schema.rb"
    - "bin/**/*"

# Gemspec rules
Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow longer classes in test controllers (they're comprehensive test suites)
Metrics/ClassLength:
  Max: 100
  Exclude:
    - "spec/**/*"
    - "spec/dummy/app/controllers/testing/**/*"
    - "spec/dummy/app/controllers/users_controller.rb"
    - "scripts/**/*"

# Allow longer methods in test files and migrations
Metrics/MethodLength:
  Max: 15
  Exclude:
    - "spec/**/*"
    - "spec/dummy/db/migrate/**/*"

# Allow higher complexity in test files and migrations  
Metrics/AbcSize:
  Max: 25
  Exclude:
    - "spec/**/*"
    - "spec/dummy/db/migrate/**/*"
    - "spec/dummy/app/controllers/testing/testing_controller.rb"
    - "spec/dummy/app/controllers/users_controller.rb"

# Style rules
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Metrics - be more lenient for tests and demo files
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "demo.rb"
    - "*.gemspec"

# Layout rules
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

# Lint rules
Lint/ScriptPermission:
  Exclude:
    - "demo.rb"
    - "scripts/**/*"

Lint/Debugger:
  Exclude:
    - "spec/**/*"

Lint/NonAtomicFileOperation:
  Exclude:
    - "scripts/**/*"

# Rails-specific disabled for now since we don't have rubocop-rails gem
# Rails/FilePath:
#   Enabled: false
