AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

# Exclude generated/vendor files
  Exclude:
    - "vendor/**/*"
    - "spec/dummy/bin/**/*"
    - "spec/dummy/config/puma.rb"
    - "spec/dummy/config/environments/**/*"
    - "spec/dummy/config/initializers/**/*"
    - "spec/dummy/db/schema.rb"
    - "bin/**/*"

# Gemspec rules
Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow longer classes in test controllers and complex analyzers
Metrics/ClassLength:
  Max: 100
  Exclude:
    - "spec/**/*"
    - "spec/dummy/app/controllers/testing/**/*"
    - "spec/dummy/app/controllers/users_controller.rb"
    - "scripts/**/*"
    - "lib/dbwatcher/services/diagram_analyzers/**/*"
    - "lib/dbwatcher/services/diagram_error_handler.rb"
    - "lib/dbwatcher/services/mermaid_syntax_builder.rb"
    - "lib/dbwatcher/services/api/summary_data_service.rb"
    - "lib/dbwatcher/services/diagram_data/**/*"
    - "lib/dbwatcher/services/analyzers/**/*"

# Allow longer methods in test files and complex analyzers
Metrics/MethodLength:
  Max: 15
  Exclude:
    - "spec/**/*"
    - "lib/dbwatcher/services/diagram_analyzers/**/*"
    - "lib/dbwatcher/services/diagram_error_handler.rb"
    - "lib/dbwatcher/services/mermaid_syntax_builder.rb"
    - "lib/dbwatcher/services/diagram_data/**/*"
    - "lib/dbwatcher/services/api/**/*"

# Allow higher complexity in test files and complex analyzers
Metrics/AbcSize:
  Max: 25
  Exclude:
    - "spec/**/*"
    - "lib/dbwatcher/services/diagram_analyzers/**/*"
    - "lib/dbwatcher/services/diagram_error_handler.rb"
    - "lib/dbwatcher/services/mermaid_syntax_builder.rb"
    - "lib/dbwatcher/services/diagram_data/**/*"

# Allow higher cyclomatic complexity in analyzers
Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - "spec/**/*"
    - "lib/dbwatcher/services/diagram_analyzers/**/*"
    - "lib/dbwatcher/services/diagram_error_handler.rb"
    - "lib/dbwatcher/services/mermaid_syntax_builder.rb"
    - "lib/dbwatcher/services/diagram_data/**/*"
    - "lib/dbwatcher/services/api/**/*"

# Allow higher perceived complexity in analyzers
Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - "spec/**/*"
    - "lib/dbwatcher/services/diagram_analyzers/**/*"
    - "lib/dbwatcher/services/diagram_error_handler.rb"
    - "lib/dbwatcher/services/mermaid_syntax_builder.rb"
    - "lib/dbwatcher/services/diagram_data/**/*"

# Style rules
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Metrics - be more lenient for tests, demo files, and complex blocks
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "demo.rb"
    - "*.gemspec"
    - "config/routes.rb"
    - "lib/dbwatcher/services/diagram_analyzers/**/*"

# Layout rules
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

# Lint rules
Lint/ScriptPermission:
  Exclude:
    - "demo.rb"
    - "scripts/**/*"

Lint/Debugger:
  Exclude:
    - "spec/**/*"

Lint/NonAtomicFileOperation:
  Exclude:
    - "scripts/**/*"

# Rails-specific disabled for now since we don't have rubocop-rails gem
# Rails/FilePath:
#   Enabled: false
