name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.draft == false &&
      (
        github.actor == 'dependabot[bot]' ||
        contains(github.event.pull_request.labels.*.name, 'auto-merge-candidate')
      )

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dbwatcher-ci App Token
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DBWATCHER_CI_APP_ID }}
          private-key: ${{ secrets.DBWATCHER_CI_PRIVATE_KEY }}

      - name: Check if PR is ready for auto-merge
        id: check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_ACTOR: ${{ github.actor }}
          HAS_AUTO_MERGE_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'auto-merge-candidate') }}
        run: |
          # Debug: Print PR title for troubleshooting
          echo "DEBUG: PR_TITLE='$PR_TITLE'"
          echo "DEBUG: GITHUB_ACTOR='$GITHUB_ACTOR'"

          # Check if this is a safe dependency update
          if [[ "$GITHUB_ACTOR" == "dependabot[bot]" ]]; then
            # Parse dependabot PR title to determine update type
            # Use printf %q to safely quote the title for shell operations
            SAFE_TITLE=$(printf '%q' "$PR_TITLE")

            # Extract dependency info from various dependabot title formats:
            # "Bump gem-name from x.y.z to a.b.c"
            # "build(deps): bump gem from x.y.z to a.b.c"
            # "chore(deps-dev): bump gem from x.y.z to a.b.c"
            if printf '%s' "$PR_TITLE" | grep -qE "(Bump|bump).*from.*to|deps.*update.*to"; then
              # Check if it's a patch or minor update (safer for auto-merge)
              if printf '%s' "$PR_TITLE" | grep -qE "(patch|security)" ||
                 printf '%s' "$PR_TITLE" | grep -qE "(from|to) [0-9]+\.[0-9]+\.[0-9]+"; then
                echo "safe_update=true" >> $GITHUB_OUTPUT
                echo "reason=patch_or_security" >> $GITHUB_OUTPUT
              elif printf '%s' "$PR_TITLE" | grep -qE "(from|to) [0-9]+\.[0-9]+"; then
                # Minor version update - still relatively safe for dev dependencies
                if printf '%s' "$PR_TITLE" | grep -qE "(rspec|rubocop|rake|cucumber|yard|pry)"; then
                  echo "safe_update=true" >> $GITHUB_OUTPUT
                  echo "reason=dev_dependency_minor" >> $GITHUB_OUTPUT
                else
                  echo "safe_update=false" >> $GITHUB_OUTPUT
                  echo "reason=production_minor_update" >> $GITHUB_OUTPUT
                fi
              else
                echo "safe_update=false" >> $GITHUB_OUTPUT
                echo "reason=major_update" >> $GITHUB_OUTPUT
              fi
            else
              echo "safe_update=false" >> $GITHUB_OUTPUT
              echo "reason=unknown_format" >> $GITHUB_OUTPUT
            fi
          elif [[ "$HAS_AUTO_MERGE_LABEL" == "true" ]]; then
            echo "safe_update=true" >> $GITHUB_OUTPUT
            echo "reason=manual_label" >> $GITHUB_OUTPUT
          else
            echo "safe_update=false" >> $GITHUB_OUTPUT
            echo "reason=not_eligible" >> $GITHUB_OUTPUT
          fi

      - name: Wait for CI checks
        if: steps.check.outputs.safe_update == 'true'
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "Test Suite"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          allowed-conclusions: success

      - name: Wait for quality checks
        if: steps.check.outputs.safe_update == 'true'
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "Code Quality"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          allowed-conclusions: success

      - name: Wait for security checks
        if: steps.check.outputs.safe_update == 'true'
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "Security Scan"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          allowed-conclusions: success

      - name: Wait for compatibility checks
        if: steps.check.outputs.safe_update == 'true'
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "Compatibility Check"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          allowed-conclusions: success

      - name: Auto-approve dependabot PRs
        if: steps.check.outputs.safe_update == 'true' && github.actor == 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          APPROVAL_REASON: ${{ steps.check.outputs.reason }}
        run: |
          gh pr review "$PR_NUMBER" --approve --body "Auto-approved safe dependency update ($APPROVAL_REASON)"

      - name: Enable auto-merge
        if: steps.check.outputs.safe_update == 'true'
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr merge "$PR_NUMBER" --auto --squash --delete-branch

      - name: Add comment for rejected auto-merge
        if: steps.check.outputs.safe_update == 'false'
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REASON: ${{ steps.check.outputs.reason }}
        run: |
          case "$REASON" in
            "major_update")
              MESSAGE="🚫 Auto-merge skipped: Major version updates require manual review for breaking changes."
              ;;
            "production_minor_update")
              MESSAGE="⚠️ Auto-merge skipped: Production dependency minor updates require manual review."
              ;;
            "unknown_format")
              MESSAGE="❓ Auto-merge skipped: Unable to determine update type from PR title."
              ;;
            *)
              MESSAGE="ℹ️ Auto-merge skipped: $REASON"
              ;;
          esac

          gh pr comment "$PR_NUMBER" --body "$MESSAGE"

  notify-auto-merge:
    runs-on: ubuntu-latest
    needs: auto-merge
    if: always() && github.actor == 'dependabot[bot]'
    steps:
      - name: Notify Slack about auto-merge
        if: needs.auto-merge.result == 'success'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "🤖 Auto-merged: ${{ github.event.pull_request.title }}",
              "username": "dbwatcher",
              "icon_emoji": ":mag:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🤖 *Auto-merged* dependency update"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View PR"
                    },
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "_${{ github.event.pull_request.title }}_"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "By ${{ github.actor }} • <https://github.com/${{ github.repository }}|${{ github.repository }}>"
                    }
                  ]
                }
              ]
            }
