name: Sync Labels

on:
  push:
    branches: [ main, master ]
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync GitHub Labels
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
          exclude: |
            help*
            *issue
